version: "3.7"

networks:
    app:
        driver: bridge

services:
    shortu:
        build: .
        environment:
            - PG_USER=${PG_USER}
            - PG_HOST=${PG_HOST}
            - PG_DB=${PG_DB}
            - PG_TIMEOUT=${PG_TIMEOUT}
            - PG_PASSWORD=${PG_PASSWORD}
            - SRV_HOST=${SRV_HOST}
            - SRV_PORT=${SRV_PORT}
            - REDIS_HOST=${REDIS_HOST}
        depends_on:
            - db
            - cache
        networks:
            - app
        ports:
            - '8080:8080'
        command:
            sh -c '/app/wait_for.sh db:5432 -t 10 -- /app/wait_for.sh cache:6379 -t 10 -- /app/tern migrate -c /app/tern.conf --migrations /app/sqls && /app/main'
    db:
        image: postgres:11.12-alpine
        restart: always
        environment:
            - POSTGRES_DB=${PG_DB}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - app
    cache:
        image: 'bitnami/redis:latest'
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379'
        networks:
            - app

